### ISSUE TITLE
iOS images generated in wrong folder since update

### ISSUE THREAD

**Issue by StephanBeutel** [rknell/cordova-media-generator#10]
Images are created in platforms/ios/NAME/Resources/icons and platforms/ios/NAME/Resources/spash.

New XCode needs images in platforms/ios/NAME/Images.xcassets/AppIcon.appiconset and platforms/ios/NAME/Images.xcassets/LaunchImage.launchimage

Also some image sizes are not needed anymore (icon-40@3x, icon-60) but other sizes are needed now (icon-83.5@2x).

**Comment by rknell** [comment]
Cheers Stephan,

I'll take a look at it and see how we go. I have done a fair bit of work
that hasn't yet been published to bring it up to scratch with the latest
cordova (including using the now working config.xml to add the generated
assets). Once it get it up I will merge in your changes.

R

<http://www.snappy-apps.com.au>

**Comment by rknell** [comment]
In the new version just pushed up it changes the way the icons etc work using cordova's copy system so should hopefully fix this going forward. Thanks for your help!
