### ISSUE TITLE
Transparent background of generated icon

### ISSUE THREAD

**Issue by StephanBeutel** [rknell/cordova-media-generator#6]
My source icon has a transparent background. The generated icons does not.

Is there any possibility to get the background transparent?

**Comment by rknell** [comment]
Hi,

I just tried throwing null into the background section and that seems to work for me

eg mediagen-config.json
```json
{
    "icon": {
        "filename": "logo.png",
        "background": null
    },
    "splash": {
        "filename": "splash.jpg",
        "background": "ee593b"
    },
    "customImages": [

    ],
    "screenshots": [

    ]
}

**Comment by nofxx** [comment]
Also, alpha works for me:

    "background": "000000ff"
