### ISSUE TITLE
Execution requires phantomjs, add to prerequisites? 

### ISSUE THREAD

**Issue by lexaux** [rknell/cordova-media-generator#9]
Hi! 

I was getting a (usual) strange error from node, with a lot of details like `spawn EACCESS` when trying to generate set of icons for the app. I had both GM and imagemagick, so that was not the case. 

The stack suggested that it was about the Phantom, so once I've installed it, things gone better. 

Probably worth adding that to the `readme.md` just in case? Or make it optional? 

Cheers,
Alex.

**Comment by rknell** [comment]
PhantomJS has been pulled out now. Might look at adding support soon for the new Chrome headless as it *should* do a better job at rendering the screenshots accurately.
